version: "3.8"
services:
  tg-bot:
    image: aiogram_bot:0.1
    container_name: tg-bot
    volumes:
      - /Users/vadimsosnin/Desktop/MCBiomsChecker:/source/
    environment:
      - TELEGRAM_TOKEN=6924062403:AAG_bZ2jhjNo5Ahmriz128zAuINmBkbgal4
    networks:
      - MCbot_network
    depends_on:
      - redis
    command: ["python3", "/source/start_bot.py"]

  redis:
    image: redis:latest
    networks:
      - MCbot_network
    ports:
      - "6379:6379"

networks:
  MCbot_network:
    name: MCbot_network
    driver: bridge






