version: "3.8"
services:
  tg-bot:
    build:
      context: .
      dockerfile: dockerfile
    container_name: tg-bot
    volumes:
      - /Users/vadimsosnin/Desktop/MCBiomsChecker:/source/
    env_file:
      - .env
    networks:
      - MCbot_network
    command: ["python3", "start_bot.py"]
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - MCbot_network
    ports:
      - "6379:6379"

networks:
  MCbot_network:
    name: MCbot_network
    driver: bridge