from enum import Enum


class AvailableLanguages(Enum):
    RU = "RU"
    EN = "EN"


class MessageHandlersAnswers(Enum):
    CHANGE_LANGUAGE_MSG = 'CHANGE_LANGUAGE_MSG'
    CHOSEN_LANGUAGE = 'CHOSEN_LANGUAGE'
    CHOSEN_LANGUAGE_HINT = 'CHOSEN_LANGUAGE_HINT'
    ALREADY_AUTHORIZED = 'ALREADY_AUTHORIZED'
    GREETINGS_MSG = 'GREETINGS_MSG'
    SELECT_LANGUAGE = "SELECT_LANGUAGE"
    HELP_MSG = 'HELP_MSG'
    NO_MAP_LETS_ADD_MSG = 'NO_MAP_LETS_ADD_MSG'
    YOUR_MAP_LIST = 'YOUR_MAP_LIST'
    SELECT_MAP_FOR_DELETING = 'SELECT_MAP_FOR_DELETING'
    NO_MAP_FOR_DELETING = "NO_MAP_FOR_DELETING"
    SELECT_STANDARD_MAP_FOR_DELETING = 'SELECT_STANDARD_MAP_FOR_DELETING'
    YOURE_NOT_AN_ADMIN = "YOURE_NOT_AN_ADMIN"


class CallbackQueriesAnswers(Enum):
    NO_THIS_MC_VERSION = 'NO_THIS_MC_VERSION'
    SUCCESSFULLY_DELETED = 'SUCCESSFULLY_DELETED'
    MAP_LIST = 'MAP_LIST'
    STANDARD_FILE_DELETED = 'STANDARD_FILE_DELETED'
    ACTION_CANCELED = 'ACTION_CANCELED'


class ButtonsLocalization(Enum):
    BACK_TO_MENU = "BACK_TO_MENU"
    ADD_FIRST_MAP = "ADD_FIRST_MAP"
    CANCEL_ACTION = "CANCEL_ACTION"
